### ISSUE TITLE
ARM  授权提示错误 KEY is EASY_ACTIVATE_TIME_ERR!

### ISSUE THREAD

**Issue by northyzq** [EasyDarwin/EasyRTSPClient#7]
Hi3520DV200  在紫鲸开放平台申请授权后, 仍然提示错误 KEY is EASY_ACTIVATE_TIME_ERR!

![image](https://user-images.githubusercontent.com/10533623/45988653-88639100-c0aa-11e8-9ce9-50e1ad4bb00a.png)

![image](https://user-images.githubusercontent.com/10533623/45988596-56522f00-c0aa-11e8-8bcd-32f88e5fe21e.png)

![image](https://user-images.githubusercontent.com/10533623/45988623-679b3b80-c0aa-11e8-8ed8-74b4d91abf35.png)

**Comment by babosa** [comment]
support@easydarwin.org
